### ISSUE TITLE
BUG报告&&个人建议&&问题

### ISSUE THREAD

**Issue by lyjjl** [MolokyMC/PridePlus#14]
BUG报告
1.少数情况下所有UI都会偏移到屏幕右下角，无法正常通过GUI修改配置/退出游戏
2.该客户端会导致某些服务器内物品异常（失效）
3.BypassAntiForge有时会导致无法进服
4.PingSpoof会导致不论何种网络环境均会因延迟过高掉线（即使是本地服务器）
5.scaffold内置参数有概率会导致消耗方块但不会搭路（即使是本地原版无反服务器）鬼知道方块那里去了）：
建议
1.希望增加类似inertiaclient的内置ViaVersion功能
2.希望能丰富HUD组件
3.希望将删减的功能重新添加
4.希望添加自动图腾、水晶等无政府/CPVP功能
5.希望优化RAM使用
6.希望优化KillAura和LegitAura的转头，使其更加平滑
7.希望增加Disable的可定制性
8.希望在trigger中增加自动打人距离控制
9.希望增加 “跳舞”（疯狂旋转） 功能
10.希望增加TNTFly
11.我需要TPArea
12.有没有可能增加对高版本和1.8.9的支持？
问题
1.bungeecordspoof有什么作用？

**Comment by MolokyMC** [comment]
bug部分除了第三条都会尝试修复。你可能在玩花雨庭服务器，它强制要求使用Forge端进服。

**Comment by MolokyMC** [comment]
你的建议部分除了第三条和最后两条都是PridePlus未来计划中的部分，不在计划中的不受考虑

**Comment by MolokyMC** [comment]
bing.com -> what is bungeecordspoof

**Comment by lyjjl** [comment]
谢谢
