### ISSUE TITLE
对于新功能的又一点想法

### ISSUE THREAD

**Issue by lyjjl** [MolokyMC/PridePlus#15]
1.我们都知道，pp在输入聊天框命令时用.作为命令提示词，如.binds 。而有些服务器会针对这个做文章，也有许多人用这个鉴别外挂。如落花星雨登录时要求聊天框输入.l 密码 登录，所以可不可以让用户可以自定义命令提示符如改成；或：之类的。
2. 可不可以增加比如你是正面击打，然后发包进行一个小tp，使你的攻击变为侧面攻击，当然，这个实现方法仅供参考
3. 对于各种涉及随机的功能，有可能让用户自选随机数算法吗？
4. 可否添加自动钓鱼竿的功能？
5. 我们都知道mc在同时按住w和a或w和d时有速度加成，所以可否利用这个做一个legitspeed，视角问题相当好解决
6. 能否在bowaimbot中加入预判射击功能
7. 能否加入对于minecraft命令的输入提示支持？（虽然这不太可能）

**Comment by catx-feitu** [comment]
功能1 可通过.say解决其实

**Comment by lyjjl** [comment]
@catx-feitu 若止言两句未为简易，若言十百千句，则极为神速

**Comment by MolokyMC** [comment]
reply
1.会考虑做toggle
2.无法
3.会考虑，但客户端内随机数用的不多
4.行
5.应该行
6.不是特别行
7.会考虑
